name: GitHub Pages Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'reports/**'
      - 'index.html'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Git config
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
    - name: Check for changes
      run: |
        git status

    - name: Setup Pages
      uses: actions/configure-pages@v2

    - name: Build and Deploy
      run: |
        echo "deploying to pages"
        git add .
        git commit -m "Automated SEO report and index update" || echo "Nothing to commit"
        git push https://github.com/${{ github.repository }}.git HEAD:main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
