name: GitHub Pages Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'reports/**'
      - 'index.html'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Pages
      uses: actions/configure-pages@v2

    - name: Build and Deploy
      run: |
        cp -r * .github/workflows/pages/* 
        echo "deploying to pages"
        # Stelle sicher, dass du den korrekten Ordner für GitHub Pages setzt.
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Update Pages" || echo "Nothing to commit"
        git push
